version: '2'

services:
   db:
     image: mariadb
     volumes:
       - db_data:/var/lib/mariadb
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: evtrs
       MYSQL_DATABASE: evtrs
       MYSQL_USER: evtrs
       MYSQL_PASSWORD: evtrs

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: evtrs
volumes:
    db_data:
